# Generated by Django 4.2.7 on 2023-12-07 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jerarquia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogJerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado')),
                ('id_jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jerarquia')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='jerarquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jerarquia'),
        ),
    ]
