# Generated by Django 4.2.7 on 2023-12-07 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='jerarquia',
        ),
        migrations.AddField(
            model_name='empleado',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logjerarquia',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logjerarquia',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
