# Generated by Django 4.2.7 on 2023-12-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_empleado_jerarquia_empleado_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jerarquia',
            name='area',
            field=models.CharField(default='', max_length=20),
        ),
    ]
